apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-static-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-app
  template:
    metadata:
      labels:
        app: eks-app
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: eks-app
          image: manukumarkc/eks-static-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000

